name: strangerschat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  proste_bezier_curve: ^2.0.2
  pinput: ^5.0.0
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.7.0
  smooth_page_indicator: ^1.2.0+3
  flutter_easyloading: ^3.0.5
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_red.png"
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/images/logo_red.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo_red.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo_red.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans.ttf
      - asset: assets/fonts/Arial.ttf
